jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://creativeidea-site.webflow.io'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: true
          issue_title: 'ZAP Scan Results'
          artifact_name: 'zap-scan-results'
        env:
          ZAP_AUTH_HEADER_VALUE: ${{ secrets.AUTH_HEADER_VALUE }}
          ZAP_AUTH_HEADER: ${{ secrets.AUTH_HEADER }}
          ZAP_AUTH_HEADER_SITE: ${{ secrets.AUTH_HEADER_SITE }}
