name: OWASP ZAP Scan

on:
  push:
    branches:
      - main 
jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get -y install openjdk-11-jre-headless
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar xf ZAP_2.11.0_Linux.tar.gz
          cd ZAP_2.11.0
          ./zap.sh -daemon -host 0.0.0.0 -port 8090

      - name: Run ZAP Scan
        run: |
          wget https://github.com/zaproxy/zap-cli/releases/download/v0.10.0/zap-cli-0.10.0.jar
          java -jar zap-cli-0.10.0.jar openapi -s zap-report.html -u https://creativeidea-site.webflow.io

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap-report.html
